<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>75ea9538-8941-40ab-8f5c-5387356c4530</elementGuidId>
    <imagePath></imagePath>
    <name>div_cardNumber</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/iron-pages[1]/div[1]/iron-form[1]/form[1]/div[2]/section[2]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>section:nth-of-type(2) &gt; div:nth-of-type(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section:nth-child(2) &gt; div:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/QA/Page_home/shopCheckout_object</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>