<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>37ee77fb-6670-4c07-b82d-1e119fffad79</elementGuidId>
    <imagePath></imagePath>
    <name>link_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/iron-pages[1]/header[1]/shop-button[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.iron-selected a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'FINISH')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Finish\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>FINISH</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/QA/Page_home/shopCheckout_object</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>