<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c1e163b8-1683-4dfa-81cc-41be82c02043</elementGuidId>
    <imagePath></imagePath>
    <name>link_mensTshirts2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//app-header/div[1]/shop-tabs[1]/shop-tab[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.iron-selected &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Men's T-Shirts')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Men's T-Shirts\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Men's T-Shirts</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/QA/Page_home/shopApp_object</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>