<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a7a937e2-c9cd-4a59-bd3b-019bf975fe67</elementGuidId>
    <imagePath></imagePath>
    <name>p_demoCheckoutComplete</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/iron-pages[1]/header[1]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.iron-selected &gt; p</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#pages p &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/QA/Page_home/shopCheckout_object</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>c4008682-6bc3-4069-80c1-75279d1f14d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>