<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>367a1a55-4915-4177-919a-fb8954c3be2f</elementGuidId>
    <imagePath></imagePath>
    <name>shopApp_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/shop-app[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>shop-app</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>shop-app</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>